library(fastDummies)
library(jsonlite)
library(scales)
json_data <- fromJSON("D:\\sem6-pracs\\ds\\prac2\\data.json")
df <- as.data.frame(json_data)
columns_to_normalize <- c("Sales", "Cost", "Profit")
df[columns_to_normalize] <- scale(df[columns_to_normalize])
df[columns_to_normalize] <- lapply(df[columns_to_normalize], rescale, to = c(0, 1))
print(df)
dummy_cols(df, select_columns = c("Product", "Category"))
