mydata <- data.frame(iris)
attach(mydata)
instal1.packages("rpart")
library(rpart)
model <- rpart(species ~ Sepal. Length + Sepal.width + Petal. Length + Petal.width, data=mydata, method="class")
plot(mode1)
text(model,use.n=TRUE, all=TRUE,cex=0.8)
instal1.packages("tree")
library(tree)
model1 <- tree(Species ~ Sepal. Length + Sepal.width + Petal. Length + Petal. width, data=mydata, method="class", split="gini")
plot (mode11)
text(model1, all=TRUE, cex=0.6)
install.packages ("party")
library(party)
mode12 <- ctree(Species ~ Sepal. Length + Sepal.width + Petal. Length + Petal.width, data=mydata)
plot(mode12)
library(tree)
mydata <- data. frame(iris)
attach(mydata)
model1 <- tree(Species ~ Sepal. Length + Sepal.width + Petal.Length + Petal.width, data=mydata, method="class", control = tree. control (nobs
150, mincut = 10))
plot(mode11)
text(mode11, all-TRUE, cex=0.6)
predict(mode11, iris)
mode12 <- ctree(Species ~ Sepal.Length + Sepal.width + Petal. Length + Petal.width, data = mydata, controls = ctree_control(maxdepth=2))
plot(mode12)
